global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["prometheus:9090"]   # or "localhost:9090" also works from itself

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
      - targets: ["node-exporter:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
